version: '3'

services:
  dotnet-publish-nuget:
    image: dotnet.publish.nuget
    build:
      context: .
      dockerfile: Dockerfile_PublishNuget
    environment:
      - VERSION=${VERSION}
      - NUGET_FOLDER=${NUGET_FOLDER}
      - API_KEY=${API_KEY}